export const phones = [
    {
        "asin": "B0CMTZNPXR",
        "product_title": "Redmi 13C (Starshine Green, 4GB RAM, 128GB Storage) | Powered by 4G MediaTek Helio G85 | 90Hz Display | 50MP AI Triple Camera",
        "product_price": "₹7,699",
        "product_original_price": "₹11,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 4644,
        "product_url": "https://www.amazon.in/dp/B0CMTZNPXR",
        "product_photo": "https://m.media-amazon.com/images/I/71hj88T5aBL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹7,699",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CMTW9MVK",
        "product_title": "Redmi 13C (Stardust Black, 6GB RAM, 128GB Storage) | Powered by 4G MediaTek Helio G85 | 90Hz Display | 50MP AI Triple Camera",
        "product_price": "₹8,499",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 4644,
        "product_url": "https://www.amazon.in/dp/B0CMTW9MVK",
        "product_photo": "https://m.media-amazon.com/images/I/71d1ytcCntL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQG4RX37",
        "product_title": "POCO C65 Pastel Blue 4GB RAM 128GB ROM",
        "product_price": "₹6,799",
        "product_original_price": "₹10,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 515,
        "product_url": "https://www.amazon.in/dp/B0CQG4RX37",
        "product_photo": "https://m.media-amazon.com/images/I/51Zjp5fq1EL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹6,799",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CMTY5P4V",
        "product_title": "Redmi 13C (Starfrost White, 4GB RAM, 128GB Storage) | Powered by 4G MediaTek Helio G85 | 90Hz Display | 50MP AI Triple Camera",
        "product_price": "₹7,699",
        "product_original_price": "₹11,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 4644,
        "product_url": "https://www.amazon.in/dp/B0CMTY5P4V",
        "product_photo": "https://m.media-amazon.com/images/I/71scmEdSC2L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹7,699",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQG9N4Z3",
        "product_title": "POCO C65 Matte Black 4GB RAM 128GB ROM",
        "product_price": "₹6,799",
        "product_original_price": "₹10,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 515,
        "product_url": "https://www.amazon.in/dp/B0CQG9N4Z3",
        "product_photo": "https://m.media-amazon.com/images/I/51PQfSwIqyL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹6,799",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQVP5ZZF",
        "product_title": "POCO M6 5G (Orion Blue, 8GB RAM, 256GB Storage)",
        "product_price": "₹10,999",
        "product_original_price": "₹15,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 338,
        "product_url": "https://www.amazon.in/dp/B0CQVP5ZZF",
        "product_photo": "https://m.media-amazon.com/images/I/71jkM1zB22L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹10,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "3K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CMTWJ5RV",
        "product_title": "Redmi 13C (Starshine Green, 6GB RAM, 128GB Storage) | Powered by 4G MediaTek Helio G85 | 90Hz Display | 50MP AI Triple Camera",
        "product_price": "₹8,499",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 4644,
        "product_url": "https://www.amazon.in/dp/B0CMTWJ5RV",
        "product_photo": "https://m.media-amazon.com/images/I/71hj88T5aBL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CY299SKS",
        "product_title": "POCO C65 Pastel Green 4GB RAM 128GB ROM",
        "product_price": "₹6,799",
        "product_original_price": "₹10,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 515,
        "product_url": "https://www.amazon.in/dp/B0CY299SKS",
        "product_photo": "https://m.media-amazon.com/images/I/51NkHXXapeL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹6,799",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQM6GXZB",
        "product_title": "POCO C65 Pastel Blue 6GB RAM 128GB ROM",
        "product_price": "₹7,499",
        "product_original_price": "₹11,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 515,
        "product_url": "https://www.amazon.in/dp/B0CQM6GXZB",
        "product_photo": "https://m.media-amazon.com/images/I/51Zjp5fq1EL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹7,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCR6TNK",
        "product_title": "Samsung Galaxy M14 5G (ICY Silver,6GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|12GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": "₹12,490",
        "product_original_price": "₹18,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCR6TNK",
        "product_photo": "https://m.media-amazon.com/images/I/81ZSn2rk9WL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0B9YK24TF",
        "product_title": "Nokia 2660 Flip 4G Volte keypad Phone with Dual SIM, Dual Screen, inbuilt MP3 Player &amp; Wireless FM Radio | Black",
        "product_price": "₹4,299",
        "product_original_price": "₹5,899",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 4384,
        "product_url": "https://www.amazon.in/dp/B0B9YK24TF",
        "product_photo": "https://m.media-amazon.com/images/I/61RBrScYUSL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹4,299",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B07WDKLPFM",
        "product_title": "vivo Y18e (Space Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers | Without Charger",
        "product_price": "₹7,999",
        "product_original_price": "₹11,999",
        "currency": "INR",
        "product_star_rating": "3.2",
        "product_num_ratings": 10,
        "product_url": "https://www.amazon.in/dp/B07WDKLPFM",
        "product_photo": "https://m.media-amazon.com/images/I/61ZBxbrVF0L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹7,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQ7RQ5RK",
        "product_title": "TECNO POP 8 (Gravity Black,(8GB*+64GB)| 90Hz Punch Hole Display with Dynamic Port &amp; Dual Speakers with DTS| 5000mAh Battery |10W Type-C| Side Fingerprint Sensor| Octa-Core Processor",
        "product_price": "₹6,899",
        "product_original_price": "₹7,799",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 1594,
        "product_url": "https://www.amazon.in/dp/B0CQ7RQ5RK",
        "product_photo": "https://m.media-amazon.com/images/I/61wbxpNaD1L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹6,899",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "4K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CX74JKLL",
        "product_title": "Nothing Phone (2a) 5G (Black, 8GB RAM, 256GB Storage) | Up to 16 GB RAM | 6.7&quot; AMOLED Display | 50MP (OIS) + 50 MP | 32 MP Front | Mediatek Dimensity 7200 Pro Processor | 45 W Charging 100% in 59 mins",
        "product_price": "₹27,394",
        "product_original_price": "₹27,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 113,
        "product_url": "https://www.amazon.in/dp/B0CX74JKLL",
        "product_photo": "https://m.media-amazon.com/images/I/71ChLWTLXqL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹27,394",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "400+ bought in past month",
        "delivery": "Only 2 left in stock."
      },
      {
        "asin": "B09G9HD6PD",
        "product_title": "Apple iPhone 13 (128GB) - Midnight",
        "product_price": "₹52,090",
        "product_original_price": "₹59,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G9HD6PD",
        "product_photo": "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹52,090",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B09G9D8KRQ",
        "product_title": "Apple iPhone 13 (128GB) - Starlight",
        "product_price": "₹52,090",
        "product_original_price": "₹59,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G9D8KRQ",
        "product_photo": "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹52,090",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B09G9BL5CP",
        "product_title": "Apple iPhone 13 (128GB) - Blue",
        "product_price": "₹52,090",
        "product_original_price": "₹59,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G9BL5CP",
        "product_photo": "https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹52,090",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "3K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B09G9FPGTN",
        "product_title": "Apple iPhone 13 (128GB) - Pink",
        "product_price": "₹52,090",
        "product_original_price": "₹59,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G9FPGTN",
        "product_photo": "https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹52,090",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "3K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B09V4B6K53",
        "product_title": "Apple iPhone 13 (128GB) - Green",
        "product_price": "₹52,090",
        "product_original_price": "₹59,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09V4B6K53",
        "product_photo": "https://m.media-amazon.com/images/I/61-r9zOKBCL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹52,090",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHX1W1XY",
        "product_title": "Apple iPhone 15 (128 GB) - Black",
        "product_price": "₹73,100",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 1645,
        "product_url": "https://www.amazon.in/dp/B0CHX1W1XY",
        "product_photo": "https://m.media-amazon.com/images/I/71657TiFeHL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹73,100",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BDHX8Z63",
        "product_title": "Apple iPhone 14 (128 GB) - Midnight",
        "product_price": "₹62,800",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 5222,
        "product_url": "https://www.amazon.in/dp/B0BDHX8Z63",
        "product_photo": "https://m.media-amazon.com/images/I/61cwywLZR-L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹62,800",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "300+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHWZCY43",
        "product_title": "Apple iPhone 15 Plus (128 GB) - Green",
        "product_price": "₹82,600",
        "product_original_price": "₹89,900",
        "currency": "INR",
        "product_star_rating": "4.6",
        "product_num_ratings": 784,
        "product_url": "https://www.amazon.in/dp/B0CHWZCY43",
        "product_photo": "https://m.media-amazon.com/images/I/71ZP6U9sWTL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹82,600",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "300+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHX3TW6X",
        "product_title": "Apple iPhone 15 (128 GB) - Pink",
        "product_price": "₹73,100",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 1645,
        "product_url": "https://www.amazon.in/dp/B0CHX3TW6X",
        "product_photo": "https://m.media-amazon.com/images/I/71v2jVh6nIL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹73,100",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "400+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B09G93H3BR",
        "product_title": "Apple iPhone 13 (256GB) - Blue",
        "product_price": "₹59,900",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G93H3BR",
        "product_photo": "https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹59,900",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHX2F5QT",
        "product_title": "Apple iPhone 15 (128 GB) - Blue",
        "product_price": "₹73,100",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 1645,
        "product_url": "https://www.amazon.in/dp/B0CHX2F5QT",
        "product_photo": "https://m.media-amazon.com/images/I/71d7rfSl0wL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹73,100",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BDK62PDX",
        "product_title": "Apple iPhone 14 (128 GB) - Blue",
        "product_price": "₹62,800",
        "product_original_price": "₹79,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 5222,
        "product_url": "https://www.amazon.in/dp/B0BDK62PDX",
        "product_photo": "https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹62,800",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B09G9BFKZN",
        "product_title": "Apple iPhone 13 (256GB) - Starlight",
        "product_price": "₹59,900",
        "product_original_price": "₹69,900",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 27438,
        "product_url": "https://www.amazon.in/dp/B09G9BFKZN",
        "product_photo": "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹59,900",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHWV2WYK",
        "product_title": "Apple iPhone 15 Pro Max (256 GB) - Black Titanium",
        "product_price": null,
        "product_original_price": null,
        "currency": null,
        "product_star_rating": "4.5",
        "product_num_ratings": 285,
        "product_url": "https://www.amazon.in/dp/B0CHWV2WYK",
        "product_photo": "https://m.media-amazon.com/images/I/81Os1SDWpcL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": null,
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "100+ bought in past month",
        "delivery": null
      }
    ,
    {
        "asin": "B0BSNP46QP",
        "product_title": "OnePlus 11R 5G (Sonic Black, 8GB RAM, 128GB Storage)",
        "product_price": "₹27,999",
        "product_original_price": "₹39,999",
        "currency": "INR",
        "product_star_rating": "4.4",
        "product_num_ratings": 15137,
        "product_url": "https://www.amazon.in/dp/B0BSNP46QP",
        "product_photo": "https://m.media-amazon.com/images/I/61u9zN1HYCL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹27,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BY8JZ22K",
        "product_title": "OnePlus Nord CE 3 Lite 5G (Pastel Lime, 8GB RAM, 128GB Storage)",
        "product_price": "₹17,990",
        "product_original_price": "₹19,999",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 46330,
        "product_url": "https://www.amazon.in/dp/B0BY8JZ22K",
        "product_photo": "https://m.media-amazon.com/images/I/61QRgOgBx0L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹17,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C9QPJY5R",
        "product_title": "Oneplus Nord CE 3 5G (Grey Shimmer, 8GB RAM, 128GB Storage)",
        "product_price": "₹18,999",
        "product_original_price": "₹26,999",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 12508,
        "product_url": "https://www.amazon.in/dp/B0C9QPJY5R",
        "product_photo": "https://m.media-amazon.com/images/I/61abLrCfF7L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹18,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CX58MTNN",
        "product_title": "Oneplus Nord CE4 (Celadon Marble, 8GB RAM, 128GB Storage)",
        "product_price": "₹24,999",
        "product_original_price": null,
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 1829,
        "product_url": "https://www.amazon.in/dp/B0CX58MTNN",
        "product_photo": "https://m.media-amazon.com/images/I/61nxQ62qglL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹24,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CX5BZXLF",
        "product_title": "Oneplus Nord CE4 (Dark Chrome, 8GB RAM, 256GB Storage)",
        "product_price": "₹26,999",
        "product_original_price": null,
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 1829,
        "product_url": "https://www.amazon.in/dp/B0CX5BZXLF",
        "product_photo": "https://m.media-amazon.com/images/I/61g1pqSjAhL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹26,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "4K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CX59SD6C",
        "product_title": "Oneplus Nord CE4 (Celadon Marble, 8Gb Ram, 256Gb Storage), Sea Green",
        "product_price": "₹26,998",
        "product_original_price": null,
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 1829,
        "product_url": "https://www.amazon.in/dp/B0CX59SD6C",
        "product_photo": "https://m.media-amazon.com/images/I/61nxQ62qglL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹26,998",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BY8MCQ9S",
        "product_title": "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 128GB Storage)",
        "product_price": "₹17,990",
        "product_original_price": "₹19,999",
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 46330,
        "product_url": "https://www.amazon.in/dp/B0BY8MCQ9S",
        "product_photo": "https://m.media-amazon.com/images/I/61LB+d0vheL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹17,990",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "400+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CX59H5W7",
        "product_title": "Oneplus Nord CE4 (Dark Chrome, 8GB RAM, 128GB Storage)",
        "product_price": "₹24,999",
        "product_original_price": null,
        "currency": "INR",
        "product_star_rating": "4.2",
        "product_num_ratings": 1829,
        "product_url": "https://www.amazon.in/dp/B0CX59H5W7",
        "product_photo": "https://m.media-amazon.com/images/I/61g1pqSjAhL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹24,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "4K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BY8JV4PX",
        "product_title": "OnePlus Nord CE 3 Lite 5G (Pastel Lime, 8GB RAM, 256GB Storage)",
        "product_price": "₹19,999",
        "product_original_price": "₹21,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 6192,
        "product_url": "https://www.amazon.in/dp/B0BY8JV4PX",
        "product_photo": "https://m.media-amazon.com/images/I/61QRgOgBx0L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹19,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BY8L3RZ6",
        "product_title": "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 256GB Storage)",
        "product_price": null,
        "product_original_price": null,
        "currency": null,
        "product_star_rating": "4.2",
        "product_num_ratings": 46330,
        "product_url": "https://www.amazon.in/dp/B0BY8L3RZ6",
        "product_photo": "https://m.media-amazon.com/images/I/61LB+d0vheL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": null,
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C7V7VH6Q",
        "product_title": "OnePlus Nord 3 5G (Misty Green, 8GB RAM, 128GB Storage)",
        "product_price": "₹19,999",
        "product_original_price": "₹33,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 5158,
        "product_url": "https://www.amazon.in/dp/B0C7V7VH6Q",
        "product_photo": "https://m.media-amazon.com/images/I/6116+vSW+1L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹19,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C7V84BS2",
        "product_title": "OnePlus Nord 3 5G (Tempest Gray, 8GB RAM, 128GB Storage)",
        "product_price": "₹19,999",
        "product_original_price": "₹33,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 5158,
        "product_url": "https://www.amazon.in/dp/B0C7V84BS2",
        "product_photo": "https://m.media-amazon.com/images/I/71-yDa90UrL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹19,999",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "4K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQPPZWVD",
        "product_title": "OnePlus 12 (Flowy Emerald, 12GB RAM, 256GB Storage)",
        "product_price": "₹64,999",
        "product_original_price": null,
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 1540,
        "product_url": "https://www.amazon.in/dp/B0CQPPZWVD",
        "product_photo": "https://m.media-amazon.com/images/I/717Qo4MH97L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹64,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CQYMMP94",
        "product_title": "OnePlus 12R (Iron Gray, 8GB RAM, 128GB Storage)",
        "product_price": "₹37,999",
        "product_original_price": "₹39,999",
        "currency": "INR",
        "product_star_rating": "4.5",
        "product_num_ratings": 808,
        "product_url": "https://www.amazon.in/dp/B0CQYMMP94",
        "product_photo": "https://m.media-amazon.com/images/I/71XNeka-BRL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹37,999",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "3K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C45N5VPT",
        "product_title": "realme narzo N53 (Feather Gold, 4GB+64GB) 33W Segment Fastest Charging | Slim Smartphone | 90 Hz Smooth Display",
        "product_price": "₹8,999",
        "product_original_price": "₹10,999",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 9277,
        "product_url": "https://www.amazon.in/dp/B0C45N5VPT",
        "product_photo": "https://m.media-amazon.com/images/I/71dEY4Neo3L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CZS3B3PY",
        "product_title": "realme NARZO 70x 5G (Ice Blue, 6GB RAM,128GB Storage)|120Hz Ultra Smooth Display|Dimensity 6100+ 6nm 5G|50MP AI Camera|45W Charger in The Box",
        "product_price": "₹13,499",
        "product_original_price": "₹17,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 265,
        "product_url": "https://www.amazon.in/dp/B0CZS3B3PY",
        "product_photo": "https://m.media-amazon.com/images/I/71nMx5PxibL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹13,499",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0D3GZ7G25",
        "product_title": "realme NARZO N65 5G (Amber Gold 4GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
        "product_price": "₹11,499",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0D3GZ7G25",
        "product_photo": "https://m.media-amazon.com/images/I/71ocQY+G2XL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹11,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0D3GX1VFM",
        "product_title": "realme NARZO N65 5G (Deep Green 6GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
        "product_price": "₹12,499",
        "product_original_price": "₹14,999",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0D3GX1VFM",
        "product_photo": "https://m.media-amazon.com/images/I/710qN4eow2L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,499",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CX213ZZM",
        "product_title": "realme 12 5G (Woodland Green, 8GB RAM 128 GB Storage) | 108 MP 3X Zoom Portrait Camera | Trendy Watch Design | 45 W SUPERVOOC Charge | 5000 mAh Massive Battery | Dual Stereo Speakers | Dynamic Button",
        "product_price": "₹16,035",
        "product_original_price": "₹20,999",
        "currency": "INR",
        "product_star_rating": "4.3",
        "product_num_ratings": 71,
        "product_url": "https://www.amazon.in/dp/B0CX213ZZM",
        "product_photo": "https://m.media-amazon.com/images/I/610rGG8jMsL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹16,035",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CTHXNT9W",
        "product_title": "realme 12 Pro 5G (Submarine Blue, 8GB RAM 256 GB Storage)",
        "product_price": "₹24,217",
        "product_original_price": "₹31,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 533,
        "product_url": "https://www.amazon.in/dp/B0CTHXNT9W",
        "product_photo": "https://m.media-amazon.com/images/I/81QvAGRjTAL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹24,217",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0D3GYZ82S",
        "product_title": "realme NARZO N65 5G (Amber Gold 6GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
        "product_price": "₹12,499",
        "product_original_price": "₹14,999",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0D3GYZ82S",
        "product_photo": "https://m.media-amazon.com/images/I/71ocQY+G2XL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,499",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CGDQRR9Y",
        "product_title": "realme narzo 60X 5G (Stellar Green,6GB,128GB Storage) Up to 2TB External Memory | 50 MP AI Primary Camera | Segments only 33W Supervooc Charge",
        "product_price": "₹14,499",
        "product_original_price": "₹15,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 12310,
        "product_url": "https://www.amazon.in/dp/B0CGDQRR9Y",
        "product_photo": "https://m.media-amazon.com/images/I/81WimZLWH1L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹14,499",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "3K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0D3GY8SC1",
        "product_title": "realme NARZO N65 5G (Deep Green 4GB RAM, 128GB Storage) India&#x27;s 1st D6300 5G Chipset | Ultra Slim 190g Design | 120Hz Eye Comfort Display | 50MP AI Camera| Charger in The Box",
        "product_price": "₹11,499",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": null,
        "product_num_ratings": 0,
        "product_url": "https://www.amazon.in/dp/B0D3GY8SC1",
        "product_photo": "https://m.media-amazon.com/images/I/710qN4eow2L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹11,499",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CX1ZXVW1",
        "product_title": "realme 12+ 5G (Pioneer Green, 8GB RAM, 128GB Storage)| Expandable Upto 2TB |MediaTek Dimensity 7050 Processor |Ultra-Smooth AMOLED Display | 50MP Sony LYT-600 OIS Portrait Cam | 67 W SUPERVOOCCharge",
        "product_price": "₹19,498",
        "product_original_price": "₹23,999",
        "currency": "INR",
        "product_star_rating": "4.3",
        "product_num_ratings": 37,
        "product_url": "https://www.amazon.in/dp/B0CX1ZXVW1",
        "product_photo": "https://m.media-amazon.com/images/I/81qwJnwp5aL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹19,498",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CZNTK28X",
        "product_title": "realme 12X 5G (Twilight Purple, 6GB RAM, 128GB Storage)",
        "product_price": "₹13,140",
        "product_original_price": "₹17,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 32,
        "product_url": "https://www.amazon.in/dp/B0CZNTK28X",
        "product_photo": "https://m.media-amazon.com/images/I/711kX064JHL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹13,140",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CHQKRVMQ",
        "product_title": "realme NARZO 70 Pro 5G (Glass Green, 8GB RAM,128GB Storage) Dimensity 7050 5G Chipset | Horizon Glass Design | Segment 1st Flagship Sony IMX890 OIS Camera",
        "product_price": "₹19,999",
        "product_original_price": "₹24,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 1430,
        "product_url": "https://www.amazon.in/dp/B0CHQKRVMQ",
        "product_photo": "https://m.media-amazon.com/images/I/71-ZHpmFzDL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹19,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": null,
        "delivery": null
      },
      {
        "asin": "B0CGF21RCY",
        "product_title": "realme 11 5G (Glory Gold, 8GB RAM, 256GB Storage) | Dynamic Ultra Smooth Display | Up to 8GB+8GB Dynamic RAM | 108MP 3× Zoom | 16MP Selfie Camera | Dimensity 6100+ 5G Processor | 67W SUPERVOOC Charge",
        "product_price": "₹18,490",
        "product_original_price": "₹22,999",
        "currency": "INR",
        "product_star_rating": "4.1",
        "product_num_ratings": 741,
        "product_url": "https://www.amazon.in/dp/B0CGF21RCY",
        "product_photo": "https://m.media-amazon.com/images/I/715G+jeSG6L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹18,490",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "200+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CC9CGLRL",
        "product_title": "realme C53, Champion Gold, 4GB RAM, 128GB Storage",
        "product_price": "₹8,651",
        "product_original_price": "₹11,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 554,
        "product_url": "https://www.amazon.in/dp/B0CC9CGLRL",
        "product_photo": "https://m.media-amazon.com/images/I/71HhsJ0BxAL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,651",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCR6TNK",
        "product_title": "Samsung Galaxy M14 5G (ICY Silver,6GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|12GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": "₹12,490",
        "product_original_price": "₹18,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCR6TNK",
        "product_photo": "https://m.media-amazon.com/images/I/81ZSn2rk9WL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCV25LG",
        "product_title": "Samsung Galaxy M14 5G (Smoky Teal,4GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|8GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": "₹9,490",
        "product_original_price": "₹17,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCV25LG",
        "product_photo": "https://m.media-amazon.com/images/I/818VqDSKpCL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹9,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C7C28GKF",
        "product_title": "Samsung Galaxy M34 5G (Waterfall Blue,6GB,128GB)|120Hz sAMOLED Display|50MP Triple No Shake Cam|6000 mAh Battery|4 Gen OS Upgrade &amp; 5 Year Security Update|12GB RAM with RAM+|Android 13|Without Charger",
        "product_price": "₹12,999",
        "product_original_price": "₹24,499",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 15207,
        "product_url": "https://www.amazon.in/dp/B0C7C28GKF",
        "product_photo": "https://m.media-amazon.com/images/I/91L9EF-OEGL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,999",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C7C1DRK5",
        "product_title": "Samsung Galaxy M34 5G (Prism Silver,6GB,128GB)|120Hz sAMOLED Display|50MP Triple No Shake Cam|6000 mAh Battery|4 Gen OS Upgrade &amp; 5 Year Security Update|12GB RAM with RAM+|Android 13|Without Charger",
        "product_price": "₹12,999",
        "product_original_price": "₹24,499",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 15207,
        "product_url": "https://www.amazon.in/dp/B0C7C1DRK5",
        "product_photo": "https://m.media-amazon.com/images/I/91ItZJh1FDL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,999",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0C7BZX934",
        "product_title": "Samsung Galaxy M34 5G (Midnight Blue,6GB,128GB)|120Hz sAMOLED Display|50MP Triple No Shake Cam|6000 mAh Battery|4 Gen OS Upgrade &amp; 5 Year Security Update|12GB RAM with RAM+|Android 13|Without Charger",
        "product_price": "₹12,999",
        "product_original_price": "₹24,499",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 15207,
        "product_url": "https://www.amazon.in/dp/B0C7BZX934",
        "product_photo": "https://m.media-amazon.com/images/I/91fonhAtoAL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "5K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CV78R7FL",
        "product_title": "Samsung Galaxy M14 4G (Arctic Blue,4GB,64GB) | 50MP Triple Cam | 5000mAh Battery | Snapdragon 680 Processor | 2 Gen. OS Upgrade &amp; 4 Year Security Update | 8GB RAM with RAM Plus | Without Charger",
        "product_price": "₹8,900",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 88,
        "product_url": "https://www.amazon.in/dp/B0CV78R7FL",
        "product_photo": "https://m.media-amazon.com/images/I/81juPhKSZJL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,900",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCSSNV7",
        "product_title": "Samsung Galaxy M14 5G (Smoky Teal,6GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|12GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": "₹12,490",
        "product_original_price": "₹18,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCSSNV7",
        "product_photo": "https://m.media-amazon.com/images/I/818VqDSKpCL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹12,490",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "4K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0D1VLPN2W",
        "product_title": "Samsung Galaxy M15 5G (Celestial Blue,8GB RAM,128GB Storage)| 50MP Triple Cam| 6000mAh Battery|MediaTek Dimensity 6100+| 4 Gen. OS Upgrade &amp; 5 Year Security Update|Super AMOLED Display|Without Charger",
        "product_price": "₹15,999",
        "product_original_price": "₹17,999",
        "currency": "INR",
        "product_star_rating": "3.6",
        "product_num_ratings": 729,
        "product_url": "https://www.amazon.in/dp/B0D1VLPN2W",
        "product_photo": "https://m.media-amazon.com/images/I/81HaKFx7EGL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹15,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCSMP95",
        "product_title": "Samsung Galaxy M14 5G (ICY Silver,4GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|8GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": null,
        "product_original_price": null,
        "currency": null,
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCSMP95",
        "product_photo": "https://m.media-amazon.com/images/I/81ZSn2rk9WL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": null,
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": "Currently unavailable."
      },
      {
        "asin": "B0CV7KZLL4",
        "product_title": "Samsung Galaxy M14 4G (Sapphire Blue,4GB,64GB) | 50MP Triple Cam | 5000mAh Battery | Snapdragon 680 Processor | 2 Gen. OS Upgrade &amp; 4 Year Security Update | 8GB RAM with RAM Plus | Without Charger",
        "product_price": "₹8,689",
        "product_original_price": "₹13,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 59,
        "product_url": "https://www.amazon.in/dp/B0CV7KZLL4",
        "product_photo": "https://m.media-amazon.com/images/I/913EiorAS0L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹8,689",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CV7MPKNK",
        "product_title": "Samsung Galaxy M14 4G (Sapphire Blue,6GB,128GB) | 50MP Triple Cam | 5000mAh Battery | Snapdragon 680 Processor | 2 Gen. OS Upgrade &amp; 4 Year Security Update | 12GB RAM with RAM Plus | Without Charger",
        "product_price": "₹11,500",
        "product_original_price": "₹16,999",
        "currency": "INR",
        "product_star_rating": "3.9",
        "product_num_ratings": 88,
        "product_url": "https://www.amazon.in/dp/B0CV7MPKNK",
        "product_photo": "https://m.media-amazon.com/images/I/913EiorAS0L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹11,500",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "1K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0BZCWLJHK",
        "product_title": "Samsung Galaxy M14 5G (Berry Blue,4GB,128GB)|50MP Triple Cam|Segment&#x27;s Only 6000 mAh 5G SP|5nm Processor|2 Gen. OS Upgrade &amp; 4 Year Security Update|8GB RAM with RAM Plus|Android 13|Without Charger",
        "product_price": "₹9,490",
        "product_original_price": "₹17,990",
        "currency": "INR",
        "product_star_rating": "4",
        "product_num_ratings": 23842,
        "product_url": "https://www.amazon.in/dp/B0BZCWLJHK",
        "product_photo": "https://m.media-amazon.com/images/I/81pmO0iVNhL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹9,490",
        "is_best_seller": false,
        "is_amazon_choice": true,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "2K+ bought in past month",
        "delivery": null
      },
      {
        "asin": "B0CCMVQZM3",
        "product_title": "Samsung Galaxy F54 5G (Meteor Blue) (256 GB ROM) (8 GB RAM)",
        "product_price": "₹22,275",
        "product_original_price": "₹35,999",
        "currency": "INR",
        "product_star_rating": "3.6",
        "product_num_ratings": 334,
        "product_url": "https://www.amazon.in/dp/B0CCMVQZM3",
        "product_photo": "https://m.media-amazon.com/images/I/91IKi40QnlL._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹22,275",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": false,
        "climate_pledge_friendly": false,
        "sales_volume": "500+ bought in past month",
        "delivery": "Only 2 left in stock."
      },
      {
        "asin": "B0CS5Z3T4M",
        "product_title": "Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Black, 12GB, 256GB Storage)",
        "product_price": "₹1,29,999",
        "product_original_price": "₹1,34,999",
        "currency": "INR",
        "product_star_rating": "4.4",
        "product_num_ratings": 194,
        "product_url": "https://www.amazon.in/dp/B0CS5Z3T4M",
        "product_photo": "https://m.media-amazon.com/images/I/71RVuBs3q9L._AC_SX444_SY639_FMwebp_QL65_.jpg",
        "product_num_offers": 1,
        "product_minimum_offer_price": "₹1,29,999",
        "is_best_seller": false,
        "is_amazon_choice": false,
        "is_prime": true,
        "climate_pledge_friendly": false,
        "sales_volume": "100+ bought in past month",
        "delivery": null
      }
    ]


   export const CategoryData = [
        {
          "name": "All Departments",
          "id": "aps"
        },
        {
          "name": "Alexa Skills",
          "id": "alexa-skills"
        },
        {
          "name": "Amazon Devices",
          "id": "amazon-devices"
        },
        {
          "name": "Amazon Explore",
          "id": "live-explorations"
        },
        {
          "name": "Amazon Fresh",
          "id": "amazonfresh"
        },
        {
          "name": "Amazon Pharmacy",
          "id": "amazon-pharmacy"
        },
        {
          "name": "Amazon Warehouse",
          "id": "warehouse-deals"
        },
        {
          "name": "Appliances",
          "id": "appliances"
        },
        {
          "name": "Apps & Games",
          "id": "mobile-apps"
        },
        {
          "name": "Arts, Crafts & Sewing",
          "id": "arts-crafts"
        },
        {
          "name": "Audible Books & Originals",
          "id": "audible"
        },
        {
          "name": "Automotive Parts & Accessories",
          "id": "automotive"
        },
        {
          "name": "AWS Courses",
          "id": "courses"
        },
        {
          "name": "Baby",
          "id": "baby-products"
        },
        {
          "name": "Beauty & Personal Care",
          "id": "beauty"
        },
        {
          "name": "Books",
          "id": "stripbooks"
        },
        {
          "name": "CDs & Vinyl",
          "id": "popular"
        },
        {
          "name": "Cell Phones & Accessories",
          "id": "mobile"
        },
        {
          "name": "Clothing, Shoes & Jewelry",
          "id": "fashion"
        },
        {
          "name": "   Women",
          "id": "fashion-womens"
        },
        {
          "name": "   Men",
          "id": "fashion-mens"
        },
        {
          "name": "   Girls",
          "id": "fashion-girls"
        },
        {
          "name": "   Boys",
          "id": "fashion-boys"
        },
        {
          "name": "   Baby",
          "id": "fashion-baby"
        },
        {
          "name": "Collectibles & Fine Art",
          "id": "collectibles"
        },
        {
          "name": "Computers",
          "id": "computers"
        },
        {
          "name": "Credit and Payment Cards",
          "id": "financial"
        },
        {
          "name": "Digital Educational Resources",
          "id": "edu-alt-content"
        },
        {
          "name": "Digital Music",
          "id": "digital-music"
        },
        {
          "name": "Electronics",
          "id": "electronics"
        },
        {
          "name": "Garden & Outdoor",
          "id": "lawngarden"
        },
        {
          "name": "Gift Cards",
          "id": "gift-cards"
        },
        {
          "name": "Grocery & Gourmet Food",
          "id": "grocery"
        },
        {
          "name": "Handmade",
          "id": "handmade"
        },
        {
          "name": "Health, Household & Baby Care",
          "id": "hpc"
        },
        {
          "name": "Home & Business Services",
          "id": "local-services"
        },
        {
          "name": "Home & Kitchen",
          "id": "garden"
        },
        {
          "name": "Industrial & Scientific",
          "id": "industrial"
        },
        {
          "name": "Just for Prime",
          "id": "prime-exclusive"
        },
        {
          "name": "Kindle Store",
          "id": "digital-text"
        },
        {
          "name": "Luggage & Travel Gear",
          "id": "fashion-luggage"
        },
        {
          "name": "Luxury Stores",
          "id": "luxury"
        },
        {
          "name": "Magazine Subscriptions",
          "id": "magazines"
        },
        {
          "name": "Movies & TV",
          "id": "movies-tv"
        },
        {
          "name": "Musical Instruments",
          "id": "mi"
        },
        {
          "name": "Office Products",
          "id": "office-products"
        },
        {
          "name": "Pet Supplies",
          "id": "pets"
        },
        {
          "name": "Premium Beauty",
          "id": "luxury-beauty"
        },
        {
          "name": "Prime Video",
          "id": "instant-video"
        },
        {
          "name": "Smart Home",
          "id": "smart-home"
        },
        {
          "name": "Software",
          "id": "software"
        },
        {
          "name": "Sports & Outdoors",
          "id": "sporting"
        },
        {
          "name": "Subscribe & Save",
          "id": "specialty-aps-sns"
        },
        {
          "name": "Subscription Boxes",
          "id": "subscribe-with-amazon"
        },
        {
          "name": "Tools & Home Improvement",
          "id": "tools"
        },
        {
          "name": "Toys & Games",
          "id": "toys-and-games"
        },
        {
          "name": "Under $10",
          "id": "under-ten-dollars"
        },
        {
          "name": "Video Games",
          "id": "videogames"
        },
        {
          "name": "Whole Foods Market",
          "id": "wholefoods"
        }
      ]